---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: 2k6acq.nqw7v8cfg9g0usoc
    description: "default kubeadm bootstrap token"
    ttl: 24h0m0s
    usages:
      - authentication
      - signing
localAPIEndpoint:
  advertiseAddress: 192.168.20.10
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: kubernetes
controlPlaneEndpoint: kube-control-plane
certificatesDir: "/etc/kubernetes/pki"
networking:
  podSubnet: "{{ pod_cidr }}"
# apiServer:
#   extraArgs:
#     - name: service-account-signing-key-file
#       value: /etc/ca-certificates/aws-irsa/sa-signer.key
#     - name: service-account-key-file
#       value: /etc/ca-certificates/aws-irsa/sa-signer-pkcs8.pub
#     - name: api-audiences
#       value: sts.amazonaws.com
#     - name: service-account-issuer
#       value: https://s3.eu-central-1.amazonaws.com/668628784939-irsa-discovery
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
ipvs:
  strictARP: true
---
